// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProlabWeb.Api.Data;

#nullable disable

namespace ProlabWeb.Api.Migrations
{
    [DbContext(typeof(AutomateContext))]
    [Migration("20250724121159_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProlabWeb.Api.Models.LabResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("OrderingPhysician")
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<string>("RawMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<string>("SpecimenId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LabResults");
                });

            modelBuilder.Entity("ProlabWeb.Api.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataMeasurementValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsNumeric")
                        .HasColumnType("boolean");

                    b.Property<int>("LabResultId")
                        .HasColumnType("integer");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("double precision");

                    b.Property<string>("ReferenceRanges")
                        .HasColumnType("text");

                    b.Property<string>("ResultAbnormalFlags")
                        .HasColumnType("text");

                    b.Property<string>("ResultStatus")
                        .HasColumnType("text");

                    b.Property<string>("SpecimenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Units")
                        .HasColumnType("text");

                    b.Property<string>("UniversalTestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LabResultId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("ProlabWeb.Api.Models.TestResult", b =>
                {
                    b.HasOne("ProlabWeb.Api.Models.LabResult", "LabResult")
                        .WithMany("TestResults")
                        .HasForeignKey("LabResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabResult");
                });

            modelBuilder.Entity("ProlabWeb.Api.Models.LabResult", b =>
                {
                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
